Events
inna-shutka/start-react pull request #2
Opened 2023-02-22 05:23 UTC by inna-shutka

✨I add button event (alert).

2023-03-01 16:50 UTC, a1exalexander requested changes

2023-03-01 16:50 UTC, a1exalexander commented on src/components/notifications/notifications.jsx
> +    };
onClick має бути пропсом! і виконувати його треба в App

2023-03-01 16:50 UTC, a1exalexander commented on src/App/App.jsx
> +            <Notification type="error">Notification</Notification>
ось тут треба обробляти onСlick 
`<Notification onClick={() => alert('hello')} type="warning">Notification</Notification>`

так буде зрочніше у майбутньому

2023-03-05 05:36 UTC, inna-shutka commented
Виправила onClick.

2023-03-13 11:50 UTC, a1exalexander approved these changes

2023-03-14 00:37 UTC, merged